### ISSUE TITLE
no docker server (error during connect: Get http://lordgaav__dind-options:2375/v1.30/version: dial tcp: lookup lordgaav__dind-options on 10.0.1.12:53: no such host)

### ISSUE THREAD

**Issue by andrejmaya** [LordGaav/dind-options#3]
Dear @LordGaav,

when I run a job like this:

```
variables:
  DOCKER_OPTS: "--insecure-registry=172.30.0.0/16"
  DOCKER_HOST: "tcp://lordgaav__dind-options:2375"  
  DOCKER_DRIVER: overlay

stages:
- test

test-docker-server:
  image: docker:latest
  services:
      - lordgaav/dind-options:latest
  stage: test
  script:
    - docker version
```
I get following error: `error during connect: Get http://lordgaav__dind-options:2375/v1.30/version: dial tcp: lookup lordgaav__dind-options on 10.0.1.12:53: no such host`

My GitLab runner is in privileged mode.
Could you please help?
